# Generated by Django 5.2.3 on 2025-07-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва поїздки')),
                ('destination', models.CharField(max_length=100, verbose_name='Місце призначення')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Поїздка',
                'verbose_name_plural': 'Поїздки',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Дата запису')),
                ('content', models.TextField(verbose_name='Вміст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='trips.trip', verbose_name='Поїздка')),
            ],
            options={
                'verbose_name': 'Запис у журналі',
                'verbose_name_plural': 'Записи у журналі',
            },
        ),
    ]
